### ISSUE TITLE
Hugging Face Hub is unreachable, please try again later

### ISSUE THREAD

**Issue by ZebinX** [autonomousvision/navsim#93]
Hi,
1. I used the same model to upload before without any issues, but today I encountered the problem 'Hugging Face Hub is unreachable, please try again later'. The same issue is also occurring with other team member's account. Could this be a platform-related issue?
2. My submitted model often stays in the queue for more than ten hours. Is it possible to increase the testing compute resources for the competition?

Thank you.

**Comment by VVeiCao** [comment]
Hi @ZebinX ,

Hugging Face occasionally experiences brief connectivity issues. You can try again in a few hours — I just checked, and it should be working now.

If you've been stuck in the queue for several hours, feel free to DM me on Discord or email me your submission ID, and I'll check it for you. My email can be found here: https://huggingface.co/spaces/AGC2025/e2e-driving-2025

Best,
Wei

**Comment by VVeiCao** [comment]
I will close this issue, feel free to reopen it.

**Comment by ZebinX** [comment]
@VVeiCao Hi, Sorry to bother you again. I’ve been trying to submit my model all day, but I keep getting: “Hugging Face Hub is unreachable, please try again later.”

I tried other accounts too, but the issue remains. It started in the past couple of days and is now blocking our work. We'd really appreciate a quick fix. Thank you!

**Comment by VVeiCao** [comment]
Hi @ZebinX,

Sorry for that, but this bug is actually not from our side. HF has this issue from time to time, usually it comes back after several hours. 
However, we still received many successful submissions these days. Please check it regularly.

Also, regarding the long waiting time you mentioned in the email, feel free to email me with your submission ID next time. I can check that for you.

Best,
Wei

**Comment by VVeiCao** [comment]
I just checked HF is working now, maybe you can try.
